field: e2d045e2-3dc6-4cf3-8c04-a45386af6c1a # Social Media Block
fieldLayouts:
  2e6bbc14-396b-4269-9deb-1415612efe92:
    tabs:
      -
        elements:
          -
            fieldUid: fb52e73d-18c1-4598-bf42-1b39479958df # Account e.g. "Facebook" or "Instagram"
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 24d2f934-5106-4961-a508-9e1c2c0a6523 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  24d2f934-5106-4961-a508-9e1c2c0a6523: # Link
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: itemLink
    instructions: ''
    name: Link
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  fb52e73d-18c1-4598-bf42-1b39479958df: # Account e.g. "Facebook" or "Instagram"
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: itemLabel
    instructions: ''
    name: 'Account e.g. "Facebook" or "Instagram"'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: account
name: 'Social Media'
sortOrder: 1
