field: 157444bb-e53a-4eb4-a588-09fb7710813d # Location Block
fieldLayouts:
  550a0e95-3dd3-4e03-aa72-76948e1806a1:
    tabs:
      -
        elements:
          -
            fieldUid: 79d2570f-f700-4de3-a97d-71cfcbb2147e # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  79d2570f-f700-4de3-a97d-71cfcbb2147e: # __blank__
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: item
    instructions: 'e.g. "Chicago"'
    name: __blank__
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: city
name: City
sortOrder: 3
