field: b79984f8-2e51-4b9f-8356-b887f57da8fd # Call-to-Actions
fieldLayouts:
  d06c6e62-6567-4a89-92df-c95c55047538:
    tabs:
      -
        elements:
          -
            fieldUid: 8fd99288-7c12-4e97-9e07-616209a1bd9e # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 59088958-5649-44ab-993b-ae474fef4c67 # Add a link to the web page
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 895c9d65-27aa-4819-a434-9afd5ff0f4b5 # Appearance
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2a21450c-2eec-4dd9-8471-32730404d554 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2a21450c-2eec-4dd9-8471-32730404d554: # __blank__
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: external
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      multi: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Open link in new tab '
            -
              - value
              - 'true'
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  8fd99288-7c12-4e97-9e07-616209a1bd9e: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: actionText
    instructions: 'e.g. "Read the foreword by Nina Sanders"'
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  895c9d65-27aa-4819-a434-9afd5ff0f4b5: # Appearance
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: actionUI
    instructions: 'Select whether call-to-action should be displayed as text or a button. Defaults to text; opens in new tab by default.'
    name: Appearance
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Text
            -
              - value
              - text
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Button
            -
              - value
              - button
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  59088958-5649-44ab-993b-ae474fef4c67: # Add a link to the web page
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: actionURL
    instructions: 'e.g. "https://www.powells.com/my-book" '
    name: 'Add a link to the web page'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: custom
name: Custom
sortOrder: 5
