field: 1b346868-16dd-435c-b0ff-d4319de58b94 # Date Block
fieldLayouts:
  d8aa83fd-c7c6-4896-bd04-c8092c062ad6:
    tabs:
      -
        elements:
          -
            fieldUid: 77e2104f-9397-4206-877a-0aaf7f813485 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  77e2104f-9397-4206-877a-0aaf7f813485: # __blank__
    columnSuffix: null
    contentColumnType: datetime
    fieldGroup: null
    handle: item
    instructions: ''
    name: __blank__
    searchable: true
    settings:
      max: null
      min: null
      minuteIncrement: '30'
      showDate: true
      showTime: false
      showTimeZone: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Date
handle: dateOnly
name: 'Date Only'
sortOrder: 1
