field: 8bd8738f-1331-4f55-b961-d5c2a2e44f53 # Chyron Content
fieldLayouts:
  987a3a90-08e4-4c93-884e-9ce5c48f75bd:
    tabs:
      -
        elements:
          -
            fieldUid: 24dfedab-186e-4f9c-92c3-d07cec6478bc # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b3308f83-ddf3-4cb2-8918-e1fe0fc4c8c6 # Entry
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  24dfedab-186e-4f9c-92c3-d07cec6478bc: # Content
    columnSuffix: qmxexxre
    contentColumnType: text
    fieldGroup: null
    handle: itemContent
    instructions: 'Brief prompt (max 120 chars)'
    name: Content
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Chyron.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b3308f83-ddf3-4cb2-8918-e1fe0fc4c8c6: # Entry
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemPage
    instructions: 'Connect the question to a specific project, exhibition, or event.'
    name: Entry
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Select an entry'
      showSiteMenu: false
      source: null
      sources:
        - 'section:54497447-5d94-44d4-aed1-b898e86a9b77' # Events
        - 'section:01aee8f9-1a88-4c82-b1ae-372cd5805db7' # Exhibitions
        - 'section:2098244b-aca8-47e2-98e7-0c0b057e76c9' # Projects
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: entryQuestion
name: 'Entry Question'
sortOrder: 1
