field: b4c86b0f-0134-4afa-8b28-6198a09c626e # Impact Module
fieldLayouts:
  6d99a013-df6c-4629-9b99-200b1f2ce47e:
    tabs:
      -
        elements:
          -
            fieldUid: fc6b0492-412d-4f80-89fc-b9b73ebdb601 # Statistic
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5ba5eada-4ccb-4ca0-a520-75a5754991f9 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5ba5eada-4ccb-4ca0-a520-75a5754991f9: # Caption
    columnSuffix: pfjziheq
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: 'Max char: 150'
    name: Caption
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Caption.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  fc6b0492-412d-4f80-89fc-b9b73ebdb601: # Statistic
    columnSuffix: hylsyutn
    contentColumnType: text
    fieldGroup: null
    handle: statistic
    instructions: ''
    name: Statistic
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: metrics
name: Metrics
sortOrder: 1
