field: 307bc9bb-3bc7-45b4-b535-976adc89de97 # Narrative Block
fieldLayouts:
  b222a883-2132-4d59-ac3d-654917ec97f5:
    tabs:
      -
        elements:
          -
            fieldUid: ab6d1ca2-b382-4307-be36-9436006194d8 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0735be14-c43b-4c21-b1f9-d7e486aa10b0 # Assign the narrative type, e.g. "Interview" or "Update"
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0735be14-c43b-4c21-b1f9-d7e486aa10b0: # Assign the narrative type, e.g. "Interview" or "Update"
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: narrativeType
    instructions: ''
    name: 'Assign the narrative type, e.g. "Interview" or "Update"'
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: '1'
      limit: null
      localizeRelations: false
      selectionLabel: 'Select one'
      showSiteMenu: false
      source: 'group:92afd0f9-75fa-4c34-87cf-55d7e10d1709' # Narrative Types
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  ab6d1ca2-b382-4307-be36-9436006194d8: # __blank__
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: item
    instructions: 'Select an existing "News," or create a new one.'
    name: __blank__
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Add a News entry'
      showSiteMenu: true
      source: null
      sources:
        - 'section:3d42007e-9de2-48c6-a935-e29a45fa3f7c' # News
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: newsNarrative
name: 'News Narrative'
sortOrder: 4
