field: a669cdfe-3072-4a16-b2cc-20c2e4f28eb9 # Spotlight Block
fieldLayouts:
  90a70a18-4f1b-486e-8f4d-788b23bf4be5:
    tabs:
      -
        elements:
          -
            fieldUid: 13c69d07-19c1-4dc3-af5a-7145671835bc # Quote Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c9d2a3a1-cf8d-4060-9704-4f800fa8de4e # Attribution
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7e5074b8-9286-4b35-9424-be7fbe9dd19b # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7e5074b8-9286-4b35-9424-be7fbe9dd19b: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: "Add an image to accompany the quote. (Optional)\r\n\r\n- Recommended minimum size: 700px x 700px\r\n\r\n- Be sure to add a *caption* that provides additional context to the image, as well as *alt text* for SEO and accessibility. \r\n**Hint:** once you've added an image, double-click its thumbnail below to update the caption and alt text."
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:486a45fd-ed4e-40c5-b637-d55222520ab5'
      defaultUploadLocationSubpath: '{% if slug %}{slug}{% endif %}'
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:486a45fd-ed4e-40c5-b637-d55222520ab5'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  13c69d07-19c1-4dc3-af5a-7145671835bc: # Quote Content
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: 'Brief quote content. Omit quotation marks. '
    name: 'Quote Content'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c9d2a3a1-cf8d-4060-9704-4f800fa8de4e: # Attribution
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: attribution
    instructions: 'Quote attribution'
    name: Attribution
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 2
