field: 98ff0f93-0148-49ba-8068-9952f61abaa8 # Event Type
fieldLayouts:
  bc3cdbaa-b0d8-47d7-ac2b-bb810e286c5e:
    tabs:
      -
        elements:
          -
            fieldUid: b0266f26-047a-4db0-b20d-5f13e1345649 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b0266f26-047a-4db0-b20d-5f13e1345649: # __blank__
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: item
    instructions: ''
    name: __blank__
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: 'Select one project or exhibition'
      showSiteMenu: true
      source: null
      sources:
        - 'section:01aee8f9-1a88-4c82-b1ae-372cd5805db7' # Exhibitions
        - 'section:2098244b-aca8-47e2-98e7-0c0b057e76c9' # Projects
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: relatedProjectOrExhibition
name: 'Connect a Project or Exhibition'
sortOrder: 2
