field: 8bd8738f-1331-4f55-b961-d5c2a2e44f53 # Chyron Content
fieldLayouts:
  00e0c48a-e083-422d-9b21-257f2c44923e:
    tabs:
      -
        elements:
          -
            fieldUid: eb3393aa-76de-405b-aac5-53732302efe3 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6cc0f341-6abb-4232-b2f0-c8c30dbb4e50 # Topic Filter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e87d9e34-bb47-4572-9a96-58f7eb8fa706 # Section Filter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 89898bb6-5352-4199-b2d8-5ed46c0bbf43 # Keyword Filter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6cc0f341-6abb-4232-b2f0-c8c30dbb4e50: # Topic Filter
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: topicFilter
    instructions: 'Connect the question to specific topics.'
    name: 'Topic Filter'
    searchable: false
    settings:
      allowLimit: false
      allowMultipleSources: false
      allowSelfRelations: false
      branchLimit: ''
      limit: null
      localizeRelations: false
      selectionLabel: 'Select a topic(s)'
      showSiteMenu: false
      source: 'group:44640def-c232-4e0a-b207-660156167038' # Topics
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Categories
  89898bb6-5352-4199-b2d8-5ed46c0bbf43: # Keyword Filter
    columnSuffix: tpwbkhdh
    contentColumnType: string(120)
    fieldGroup: null
    handle: keywordFilter
    instructions: '(Optional) Connect the question to a specific keyword.'
    name: 'Keyword Filter'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 30
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e87d9e34-bb47-4572-9a96-58f7eb8fa706: # Section Filter
    columnSuffix: shchhefz
    contentColumnType: string
    fieldGroup: null
    handle: sectionFilter
    instructions: '(Optional) Connect the question to a specific section; defaults to all sections.'
    name: 'Section Filter'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - All
            -
              - value
              - all
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Projects
            -
              - value
              - projects
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Exhibitions
            -
              - value
              - exhibitions
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Events
            -
              - value
              - events
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  eb3393aa-76de-405b-aac5-53732302efe3: # Content
    columnSuffix: etndrqfe
    contentColumnType: text
    fieldGroup: null
    handle: itemContent
    instructions: 'Brief prompt (max 120 chars)'
    name: Content
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Chyron.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: searchQuestion
name: 'Search Question'
sortOrder: 2
