field: 157444bb-e53a-4eb4-a588-09fb7710813d # Location Block
fieldLayouts:
  f6658a71-68c3-4506-bf56-6cec39d5f0f9:
    tabs:
      -
        elements:
          -
            fieldUid: b29919d5-0aa5-4e6a-a38e-29e3e9653ee0 # __blank__
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b29919d5-0aa5-4e6a-a38e-29e3e9653ee0: # __blank__
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: item
    instructions: 'e.g. "5701 S. Woodlawn Avenue"'
    name: __blank__
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: streetAddress
name: 'Street Address'
sortOrder: 2
