fieldLayouts:
  21fff19d-5055-4278-b806-17429b6cf217:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: d5c86c8a-c961-4fb2-8348-90331ee47da2 # Opener Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            template: control-panel/common/_opener-image.html
            type: craft\fieldlayoutelements\Template
            width: 100
          -
            fieldUid: dd463042-99d6-4725-b849-2546454db735 # Opener Image
            instructions: ' '
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Opener
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 34e083b7-1017-43e8-8a33-cb3b0f535740 # Director's Statement
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Director''s Statement'
        sortOrder: 2
      -
        elements:
          -
            template: control-panel/about/_impact-image.html
            type: craft\fieldlayoutelements\Template
            width: 100
          -
            fieldUid: efcf69a5-9d82-4d07-ac04-5f1ea6865944 # Impact Image
            instructions: ' '
            label: ' '
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: b4df5032-8566-4b5b-8aa6-6345a7e93081 # Body
            instructions: 'Content introducing the Impact section; no character count restriction (Recommended max char: 500). '
            label: Introduction
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: b4c86b0f-0134-4afa-8b28-6198a09c626e # Impact Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            template: control-panel/about/_impact-intro.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Impact
        sortOrder: 3
      -
        elements:
          -
            template: control-panel/about/_people-section.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: People
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 03c99505-27a8-4aa0-b166-32be2e200535 # Card Block
            instructions: ''
            label: 'Application Card'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Application Process'
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 539c4bcb-5095-490d-81b8-872d3745551f # Card Image
            instructions: 'Add an image of a map to aid in directions (Min size: 640px x 640px).'
            label: 'Visit Image'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d4ed8f4-2f3b-4320-89ac-8225fbc867d3 # Directions
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Visit the Collegium'
        sortOrder: 6
      -
        elements:
          -
            fieldUid: 31ccea3a-6188-4659-a373-d53b96a6866e # Publication Card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            template: control-panel/about/_publications-section.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Publications
        sortOrder: 7
      -
        elements:
          -
            fieldUid: 0a86b37e-908d-4b4e-9403-7714a767c878 # News Module
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            template: control-panel/about/_news-section.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: 'News & Announcements'
        sortOrder: 8
handle: aboutIndex
hasTitleField: false
name: 'About Index'
section: 447e6245-204b-41fa-91d2-d99b74c5bc72 # About Index
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
