fieldLayouts:
  3b8afe7a-e576-409d-802d-1e91c5ebdd17:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 1b346868-16dd-435c-b0ff-d4319de58b94 # Date Block
            instructions: ''
            label: 'Project Date'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e411160c-4119-4cd7-9b04-9921a260e03a # Status
            instructions: ''
            label: 'Project Status'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 7b9acf95-b9b8-48aa-ba4f-223883c1e223 # Topics
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            template: control-panel/common/_card-image.html
            type: craft\fieldlayoutelements\Template
            width: 100
          -
            fieldUid: 539c4bcb-5095-490d-81b8-872d3745551f # Card Image
            instructions: ' '
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            template: control-panel/projects/_project-opener.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Info
        sortOrder: 1
      -
        elements:
          -
            fieldUid: abf135fc-5443-48d6-bc54-cf819645a909 # Abstract
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4defd050-67bf-44b0-a585-e6a0f635921d # Summary
            instructions: "**Full project summary following the introduction**\r\nThis content can be expanded and collapsed by the visitor (it is collapsed by default)."
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            template: control-panel/projects/_project-summary.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Summary
        sortOrder: 2
      -
        elements:
          -
            fieldUid: e3631722-e9da-4086-8806-2e7a56ddf46a # Team
            instructions: ''
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Team
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 307bc9bb-3bc7-45b4-b535-976adc89de97 # Narrative Block
            instructions: "## Add as many narratives as needed. \r\n\r\nNarratives can be rearranged by drag & drop. "
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            template: control-panel/projects/_project-narrative.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Narratives
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 6217da4c-403b-4e7c-bfd0-c78365638e41 # Citations
            instructions: ''
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            template: control-panel/projects/_project-citations.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: 'Reading List'
        sortOrder: 5
      -
        elements:
          -
            fieldUid: a669cdfe-3072-4a16-b2cc-20c2e4f28eb9 # Spotlight Block
            instructions: ''
            label: __blank__
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            template: control-panel/projects/_project-spotlight.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Spotlights
        sortOrder: 6
      -
        elements:
          -
            template: control-panel/projects/_project-featured-exhibition.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: 'Related Exhibition'
        sortOrder: 7
handle: interior
hasTitleField: true
name: Interior
section: 2098244b-aca8-47e2-98e7-0c0b057e76c9 # Projects
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
