fieldLayouts:
  15bcb220-cf6b-4687-8d99-000b01d4c0d9:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 1b346868-16dd-435c-b0ff-d4319de58b94 # Date Block
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            template: control-panel/common/_opener-image.html
            type: craft\fieldlayoutelements\Template
            width: 100
          -
            fieldUid: dd463042-99d6-4725-b849-2546454db735 # Opener Image
            instructions: ' '
            label: ' '
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d5c86c8a-c961-4fb2-8348-90331ee47da2 # Opener Content
            instructions: '(Optional) Brief text introducing the entry.'
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            template: control-panel/common/_card-image.html
            type: craft\fieldlayoutelements\Template
            width: 100
          -
            fieldUid: 539c4bcb-5095-490d-81b8-872d3745551f # Card Image
            instructions: ' '
            label: ' '
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Info
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 63a1e9e8-c4a6-4d3e-a317-a8b319be6454 # Teaser
            instructions: 'Add content to represent the entry throughout the site. (Max characters: 350)'
            label: 'Brief description of news entry'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b4df5032-8566-4b5b-8aa6-6345a7e93081 # Body
            instructions: '(Optional) Content for the entry that either exceeds the brief description length requirements, or requires additional formatting; no character count restrictions.'
            label: 'Full description of news entry'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
      -
        elements:
          -
            fieldUid: a669cdfe-3072-4a16-b2cc-20c2e4f28eb9 # Spotlight Block
            instructions: "###Add as many spotlights as needed.\r\n\r\nMultiple Key Questions will be translated into slides. See screenshot below for examples."
            label: ' '
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Spotlights
        sortOrder: 3
handle: interior
hasTitleField: true
name: Interior
section: 4a13f69d-023f-4d8a-8887-a6bc8a325616 # News
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
