defaultPlacement: end
fieldLayouts:
  c46eccc8-0341-4826-bc94-060019f43099:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            template: control-panel/common/_event-results.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Content
        sortOrder: 1
handle: eventTypes
name: 'Event Types'
siteSettings:
  0c99f337-2218-4c6f-b0ad-30589c1ebbc5: # neubauer
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: aec74a7c-a2f4-4dd3-a3f0-cdb97209335c
