defaultPlacement: end
fieldLayouts:
  9bab5185-3da5-480e-919a-4ae74e43e383:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            template: control-panel/common/_topic-results.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Content
        sortOrder: 1
handle: topics
name: Topics
siteSettings:
  0c99f337-2218-4c6f-b0ad-30589c1ebbc5: # neubauer
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: e5f4ee20-8ca7-43a9-8063-7d05dce93b07
