fieldLayouts:
  624c44fd-a901-445c-9a2e-2e8a00c720b6:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: a9037236-9afc-4591-8ab0-5d1ed7c8dac6 # Alt Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 712ad535-5310-4cbf-8e0a-625c9dcd2162 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: common
hasUrls: true
name: Common
settings:
  path: '@webroot/uploads/common/'
sortOrder: 9
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: /uploads/common/
