columnSuffix: null
contentColumnType: string
fieldGroup: d3d4b2ba-3a6c-4a4d-bdf6-aac972ad191a # Common
handle: actionBlock
instructions: 'Add as many call-to-actions as needed.'
name: Call-to-Actions
searchable: false
settings:
  contentTable: '{{%matrixcontent_actionblock}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
