columnSuffix: null
contentColumnType: text
fieldGroup: 10ed9c28-61c3-4258-bc65-24b2ecaa7930 # Asset
handle: caption
instructions: 'A brief image or video caption that adds context or credit to the media. (Max character count: 250)'
name: Caption
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Caption.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
