columnSuffix: null
contentColumnType: string
fieldGroup: d3d4b2ba-3a6c-4a4d-bdf6-aac972ad191a # Common
handle: cardBlock
instructions: 'Add card modules as needed. Rearrange by drag & drop.'
name: 'Card Block'
searchable: true
settings:
  contentTable: '{{%matrixcontent_cardblock}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
