columnSuffix: null
contentColumnType: text
fieldGroup: d3d4b2ba-3a6c-4a4d-bdf6-aac972ad191a # Common
handle: displayName
instructions: 'Visitor-facing name that will display within the page opener, and within navigation (Required).'
name: 'Display Name'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
