columnSuffix: null
contentColumnType: string
fieldGroup: eb6e4b27-3a81-4da1-8f40-fa29c0f7805c # Event
handle: eventType
instructions: 'Assign a Type (e.g. "Book Signing" or "Panel") to the Event by selecting an existing type, or creating a new one. This is the label that will display above the Event''s title within the Event card.'
name: 'Event Type'
searchable: true
settings:
  contentTable: '{{%matrixcontent_eventtype}}'
  maxBlocks: '2'
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
