columnSuffix: jbsedxzx
contentColumnType: text
fieldGroup: eb6e4b27-3a81-4da1-8f40-fa29c0f7805c # Event
handle: eventLocation
instructions: ''
name: 'Event Location'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
