columnSuffix: null
contentColumnType: string
fieldGroup: eb6e4b27-3a81-4da1-8f40-fa29c0f7805c # Event
handle: eventType
instructions: 'Select "Custom" to write in an event type (e.g. "Book Signing"); select "Exhibition" or "Project" to connect a specific exhibition or project to this event. Defaults to "Custom."'
name: 'Event Type'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Custom
        -
          - value
          - custom
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Exhibition
        -
          - value
          - exhibition
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Project
        -
          - value
          - project
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
