columnSuffix: uptnycbu
contentColumnType: string(80)
fieldGroup: eb6e4b27-3a81-4da1-8f40-fa29c0f7805c # Event
handle: eventLabel
instructions: 'Label that describes the type of event, e.g. "Book Signing" '
name: 'Event Label'
searchable: false
settings:
  byteLimit: null
  charLimit: 20
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
