columnSuffix: null
contentColumnType: text
fieldGroup: 840b4f3b-b9bb-4665-8929-9d5969e6c272 # Exhibition
handle: exhbitionSummary
instructions: 'Max characters: 675'
name: 'Brief description of exhibition'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Exhibition.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: '1'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
