columnSuffix: null
contentColumnType: string
fieldGroup: d3d4b2ba-3a6c-4a4d-bdf6-aac972ad191a # Common
handle: narrativeBlock
instructions: ''
name: 'Narrative Block'
searchable: true
settings:
  contentTable: '{{%matrixcontent_narrativeblock}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
