columnSuffix: null
contentColumnType: text
fieldGroup: d718eb8e-8ecf-4c2a-ad3e-4e289eaebb2d # Homepage
handle: openerTagline
instructions: "Prominent site tagline, e.g. \"Open to Inquiry\"\r\n\r\nMax characters: 20"
name: 'Opener Tagline'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: ''
  purifyHtml: '1'
  redactorConfig: Simple.json
  removeEmptyTags: '1'
  removeInlineStyles: '1'
  removeNbsp: '1'
  showHtmlButtonForNonAdmins: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
