columnSuffix: null
contentColumnType: text
fieldGroup: 206e479c-63c6-4776-b5f2-709e81c8c2fd # Person
handle: personAffiliation
instructions: 'Person''s institutional affiliation, e.g. "DePaul University"'
name: Affiliation
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
