columnSuffix: null
contentColumnType: string
fieldGroup: d3d4b2ba-3a6c-4a4d-bdf6-aac972ad191a # Common
handle: relatedExhibition
instructions: 'Connect an exhibition to the entry.'
name: 'Related Exhibition'
searchable: true
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Add an exhibition'
  showSiteMenu: true
  source: null
  sources:
    - 'section:01aee8f9-1a88-4c82-b1ae-372cd5805db7' # Exhibitions
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
