columnSuffix: null
contentColumnType: string
fieldGroup: d3d4b2ba-3a6c-4a4d-bdf6-aac972ad191a # Common
handle: secondaryFeaturedProject
instructions: '(Optional) Select an existing Project, or create a new one, to display within the footer across individual Project pages. Defaults to a randomly selected project.'
name: 'Secondary Featured Project'
searchable: true
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Add a featured project'
  showSiteMenu: true
  source: null
  sources:
    - 'section:01aee8f9-1a88-4c82-b1ae-372cd5805db7' # Exhibitions
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
