columnSuffix: null
contentColumnType: string
fieldGroup: d3d4b2ba-3a6c-4a4d-bdf6-aac972ad191a # Common
handle: spotlightBlock
instructions: "## Add as many spotlights as needed. \r\nMultiple Key Questions will be translated into slides. See screenshot below for examples.\r\n"
name: 'Spotlight Block'
searchable: true
settings:
  contentTable: '{{%matrixcontent_spotlightblock}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
