columnSuffix: null
contentColumnType: string
fieldGroup: 47e78d01-d60c-4623-939e-b212935f0db8 # Story
handle: storyDropdown
instructions: ''
name: 'Story Dropdown'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Select a story type'
        -
          - value
          - ''
        -
          - disabled
          - true
    -
      __assoc__:
        -
          - label
          - Testing
        -
          - value
          - testing
translationKeyFormat: null
translationMethod: none
type: controlpanel\fields\StoryCategory
