field: 1b5ff85e-b240-4399-b573-d707fe1c03da # Discover More
fieldLayouts:
  b6c48406-2df2-44f1-9ec8-4d99aac08d31:
    tabs:
      -
        elements:
          -
            fieldUid: 1d2233b4-6057-429d-8554-943383539dcb # Label
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5f9f5e73-b6cf-46f5-8012-60b8301bff36 # Description
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8e497ed8-5673-40b5-a1ca-3f83b9ef05b6 # Call-to-Action
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1d2233b4-6057-429d-8554-943383539dcb: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'e.g. Visit'
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5f9f5e73-b6cf-46f5-8012-60b8301bff36: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: 'e.g. Plan your visit to our gallery or lecture hall.'
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8e497ed8-5673-40b5-a1ca-3f83b9ef05b6: # Call-to-Action
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: callToAction
    instructions: ''
    name: Call-to-Action
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_calltoaction}}'
      maxBlocks: '1'
      minBlocks: ''
      propagationKeyFormat: null
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
