field: 0d4ed8f4-2f3b-4320-89ac-8225fbc867d3 # Directions
fieldLayouts:
  dde7d370-810b-4ba0-a3a5-fdc15da4e68f:
    tabs:
      -
        elements:
          -
            fieldUid: 87ef4cab-5dca-4851-a37f-55955e5d3b85 # Details
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b171a4a0-abb4-4afa-8265-ce90caf9c0ff # Car
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 028f51f0-ce87-4a29-9df2-bf30a7cf4783 # Public Transit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  028f51f0-ce87-4a29-9df2-bf30a7cf4783: # Public Transit
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: publicTransit
    instructions: 'Directions by public transit. Collapsed by default.'
    name: 'Public Transit'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Abstract.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  87ef4cab-5dca-4851-a37f-55955e5d3b85: # Details
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: details
    instructions: 'Brief description about visiting the Collegium, including address and hours.'
    name: Details
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Abstract.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  b171a4a0-abb4-4afa-8265-ce90caf9c0ff: # Car
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: car
    instructions: 'Directions by car. Collapsed by default.'
    name: Car
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Abstract.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
