field: 1dc1a829-2d1a-40ac-a13b-7bdaf0833a08 # Link
fieldLayouts:
  66f56e50-2492-456e-abe9-d8037eea4241:
    tabs:
      -
        elements:
          -
            fieldUid: 5b3d76c6-c34a-4630-9901-1c8c7318fd33 # Label
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d2eef677-ad04-43ad-b73c-1d87978f3538 # URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5b3d76c6-c34a-4630-9901-1c8c7318fd33: # Label
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: actionText
    instructions: 'e.g. "Log into our application portal"'
    name: Label
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d2eef677-ad04-43ad-b73c-1d87978f3538: # URL
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: actionURL
    instructions: 'e.g. "https://neubauercollegium.uchicago.edu/cfp/application_login/"'
    name: URL
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
