fieldLayouts:
  50986eff-46e9-443e-b013-21441f85b6bf:
    tabs:
      -
        elements:
          -
            heading: 'Update the Search Opener'
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: d5c86c8a-c961-4fb2-8348-90331ee47da2 # Opener Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Opener
        sortOrder: 1
handle: searchIndex
name: 'Search Index'
sortOrder: 2
