fieldLayouts:
  cb701f77-25e4-40df-b632-40a5c4abf8c0:
    tabs:
      -
        elements:
          -
            template: control-panel/tutorials/_index.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Categories
        sortOrder: 1
      -
        elements:
          -
            template: control-panel/tutorials/_index.html
            type: craft\fieldlayoutelements\Template
            width: 100
        name: Chyron
        sortOrder: 2
handle: tutorials
name: Tutorials
sortOrder: 6
