defaultPlacement: end
enableVersioning: true
handle: exhibitions
name: Exhibitions
propagationMethod: all
siteSettings:
  0c99f337-2218-4c6f-b0ad-30589c1ebbc5: # neubauer
    enabledByDefault: true
    hasUrls: true
    template: exhibitions/_entry
    uriFormat: 'exhibitions/{slug}'
type: channel
