defaultPlacement: end
enableVersioning: true
handle: researchIndex
name: 'Research Index'
propagationMethod: all
siteSettings:
  0c99f337-2218-4c6f-b0ad-30589c1ebbc5: # neubauer
    enabledByDefault: true
    hasUrls: true
    template: layouts/_index.html
    uriFormat: research
type: single
